### PR TITLE
MixerAPI v2.0.0 - CakePHP 5 support

### PR DESCRIPTION
**Pull request by cnizzardini**
Add support for CakePHP 5

TODO: 
- [x] Get test suite passing
- [x] Determine if mixerapi/rest should be kept.
- [x] Manual regression test with demo app: https://github.com/mixerapi/demo

### CODE REVIEW

**Comment by cnizzardini** [comment]
@MasaKni I have merged in your changes, thank you!

**Comment by MasaKni** [comment]
hey @cnizzardini , any idea when a release will be?

**Comment by cnizzardini** [comment]
Will be releasing it's main dependency this week: https://github.com/cnizzardini/cakephp-swagger-bake

Then work on getting this released after @MasaKni

**Comment by cnizzardini** [comment]
@MasaKni if I did an RC, would you mind helping to test this?

**Comment by MasaKni** [comment]
@cnizzardini  yes I am willing to help

**Comment by MasaKni** [comment]
@cnizzardini any updates when you will release it?

**Comment by cnizzardini** [comment]
@MasaKni I've been working on the demo app: https://github.com/mixerapi/demo

Just about done. You can see the next item on the list after that is the skeleton app. After that its just documentation which should be fairly light work.

**Pull request merged**
